---
homeassistant_alexa_client:
  id: "{{ lookup('pipe', 'op read op://ansible/Alexa/username') }}"
  secret: "{{ lookup('pipe', 'op read op://ansible/Alexa/credential') }}"
homeassistant_card_mod_version: 4.2.1
homeassistant_frosted_glass_manager_version: 1.3
homeassistant_frosted_glass_version: 1.3
homeassistant_gmail:
  address: "{{ lookup('pipe', 'op read op://ansible/Gmail/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/Gmail/credential') }}"
homeassistant_token: "{{ lookup('pipe', 'op read \"op://ansible/Home Assistant/token\"') }}"
homeassistant_latlng:
  home:
    lat: "{{ lookup('pipe', 'op read \"op://ansible/Tats Shibata/latitude\"') }}"
    lng: "{{ lookup('pipe', 'op read \"op://ansible/Tats Shibata/longitude\"') }}"
homeassistant_mini_graph_card_version: 0.13.0
homeassistant_mini_media_player_version: 1.16.9
homeassistant_mosquitto_password: "{{ lookup('pipe', 'op read op://ansible/Mosquitto/credential') }}"
homeassistant_postgres:
  username: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/username\"') }}"
  password: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/password\"') }}"
  hostname: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/server\"') }}"
  db: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/database\"') }}"
homeassistant_regza:
  username: "{{ lookup('pipe', 'op read op://ansible/REGZA/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/REGZA/credential') }}"
homeassistant_simple_thermostat_version: 2.5.0
homeassistant_simple_weather_card_version: 0.8.5
homeassistant_tuya_local_version: 2026.5.4
