---
homeassistant_alexa_client:
  id: "{{ lookup('pipe', 'op read op://ansible/xpmd3wovd4mykczh67ev57x7tq/username') }}"
  secret: "{{ lookup('pipe', 'op read op://ansible/xpmd3wovd4mykczh67ev57x7tq/credential') }}"
homeassistant_card_mod_version: 4.2.1
homeassistant_frigate_version: 5.15.6
homeassistant_frosted_glass_manager_version: 1.3
homeassistant_frosted_glass_version: 1.3
homeassistant_gmail:
  address: "{{ lookup('pipe', 'op read op://ansible/pp4axkz5nfgteolioy6futabra/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/pp4axkz5nfgteolioy6futabra/credential') }}"
homeassistant_hems_echonet_lite_version: 2f17cf23bbfb2503cdc3cf239376bbfdc51fd02f  # v0.8.8
homeassistant_token: "{{ lookup('pipe', 'op read \"op://ansible/jdyfywcw5p3xcet3nxlkvlbonm/credential\"') }}"
homeassistant_latlng:
  home:
    lat: "{{ lookup('pipe', 'op read \"op://ansible/weohbz5qszb2gbs6rz6cbr2wee/latitude\"') }}"
    lng: "{{ lookup('pipe', 'op read \"op://ansible/weohbz5qszb2gbs6rz6cbr2wee/longitude\"') }}"
homeassistant_mini_graph_card_version: 0.13.0
homeassistant_mini_media_player_version: 1.16.9
homeassistant_mosquitto_password: "{{ lookup('pipe', 'op read op://ansible/utsespwfv247vhgklpbbpbtboe/credential') }}"
homeassistant_postgres:
  username: "{{ lookup('pipe', 'op read \"op://ansible/3c332at5nvnmzgten4donmsrqm/username\"') }}"
  password: "{{ lookup('pipe', 'op read \"op://ansible/3c332at5nvnmzgten4donmsrqm/password\"') }}"
  hostname: "{{ lookup('pipe', 'op read \"op://ansible/3c332at5nvnmzgten4donmsrqm/server\"') }}"
  db: "{{ lookup('pipe', 'op read \"op://ansible/3c332at5nvnmzgten4donmsrqm/database\"') }}"
homeassistant_regza:
  username: "{{ lookup('pipe', 'op read op://ansible/c5evfiztjavi7w74ollpcwrv5e/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/c5evfiztjavi7w74ollpcwrv5e/credential') }}"
homeassistant_simple_thermostat_version: 2.5.0
homeassistant_simple_weather_card_version: 0.8.5
homeassistant_tesla_fleet:
  private_key: "{{ lookup('pipe', 'op read \"op://ansible/a43jcxbfn53ohsi5hbvw7qozie/private key base64\" | openssl base64 -d -A') }}"
  public_key: "{{ lookup('pipe', 'op read \"op://ansible/a43jcxbfn53ohsi5hbvw7qozie/private key base64\" | openssl base64 -d -A | openssl ec -pubout') }}"
homeassistant_tuya_local_version: 2026.7.2
