---
- name: container | Resolve aged image
  ansible.builtin.set_fact:
    __homeassistant_ha_secondary_image: >-
      {{ lookup('aged_release', 'oci:ghcr.io/home-assistant/home-assistant', pattern='^\d{4}\.\d+\.\d+$', platform='linux/' ~ ('arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64')) }}

- name: container | Create compose directory
  ansible.builtin.file:
    path: /etc/compose/homeassistant
    state: directory
    mode: "0755"

- name: container | Deploy compose file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: /etc/compose/homeassistant/compose.yaml
    mode: "0644"
  register: __homeassistant_ha_secondary_compose

- name: container | Pull image without starting it
  community.docker.docker_compose_v2:
    project_src: /etc/compose/homeassistant
    state: stopped
    pull: missing
  when: not (ansible_check_mode and __homeassistant_ha_secondary_compose is changed)
