---
litellm_aws_access_key_id: "{{ lookup('pipe', 'op read \"op://ansible/lqqboxodgnnmnudjnuutkil7si/username\"') }}"
litellm_aws_secret_access_key: "{{ lookup('pipe', 'op read \"op://ansible/lqqboxodgnnmnudjnuutkil7si/credential\"') }}"
litellm_master_key: "{{ lookup('pipe', 'op read \"op://ansible/z4xaablyobjlntjcoogg7rvffm/master key\"') }}"
litellm_salt_key: "{{ lookup('pipe', 'op read \"op://ansible/z4xaablyobjlntjcoogg7rvffm/salt key\"') }}"
