---
dependencies:
  - role: fail2ban
    tags:
      - fail2ban
  - role: docker
    tags:
      - docker
  - role: httpd
    tags:
      - httpd
  - role: zabbix_agent
    tags:
      - zabbix_agent
