---
- name: Import tap tasks
  ansible.builtin.import_tasks: tap.yml
  tags:
    - darwin_tap

- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - darwin_package
    - update

- name: Import cask tasks
  ansible.builtin.import_tasks: cask.yml
  tags:
    - darwin_cask
    - update

- name: Import mas tasks
  ansible.builtin.import_tasks: mas.yml
  tags:
    - darwin_mas

- name: Import npm tasks
  ansible.builtin.import_tasks: npm.yml
  tags:
    - darwin_npm
    - update

- name: Import uv tasks
  ansible.builtin.import_tasks: uv.yml
  tags:
    - darwin_uv
    - update

- name: Import font tasks
  ansible.builtin.import_tasks: font.yml
  tags:
    - darwin_font
    - update

- name: Import security tasks
  ansible.builtin.import_tasks: security.yml
  tags:
    - darwin_security
    - update

- name: Import path tasks
  ansible.builtin.import_tasks: path.yml
  tags:
    - darwin_path

- name: Import xurl tasks
  ansible.builtin.import_tasks: xurl.yml
  tags:
    - darwin_xurl

- name: Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  tags:
    - darwin_cleanup

- name: Import upgrade tasks
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - darwin_upgrade
    - update
