---
- name: package | Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: package | Install formulae
  community.general.homebrew:
    name: "{{ item }}"
    update_homebrew: false
  loop: "{{ darwin_packages + darwin_extra_packages }}"

- name: package | Install Chrome for agent-browser
  ansible.builtin.command: agent-browser install
  changed_when: false

- name: package | Install PowerShell with dotnet
  ansible.builtin.command: dotnet tool install --global PowerShell
  changed_when: false
