---
- name: xurl | Configure X API authentication
  ansible.builtin.command:
    cmd: >
      xurl auth apps add kiro-rewse
      --client-id "{{ lookup('pipe', 'op read op://ansible/3mpawbf6a3ipmepznocniqqes4/username') }}"
      --client-secret "{{ lookup('pipe', 'op read op://ansible/3mpawbf6a3ipmepznocniqqes4/credential') }}"
    creates: ~/.xurl
  no_log: true
