---
- name: Reload Apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Restart zabbix-server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
