---
- name: Configure personal Mac
  hosts: darwin_personal
  connection: local
  roles:
    - role: darwin
      tags:
        - darwin
    - role: chezmoi
      tags:
        - chezmoi
    - role: nix
      tags:
        - nix
    - role: power_monitor
      tags:
        - power_monitor
    - role: restic
      tags:
        - restic
