---
- name: Configure business Mac
  hosts: darwin_business
  connection: local
  roles:
    - role: darwin
      tags:
        - darwin
    - role: chezmoi
      tags:
        - chezmoi
    - role: builder_toolbox
      tags:
        - builder_toolbox
