---
- name: Configure home secondary
  hosts: home_secondary
  become: true
  remote_user: ubuntu
  roles:
    - role: ubuntu
      tags:
        - ubuntu
    - role: raspberrypi
      tags:
        - raspberrypi
    - role: chezmoi
      tags:
        - chezmoi
    - role: postfix_client
      tags:
        - postfix_client
    - role: zabbix_agent
      tags:
        - zabbix_agent
    - role: fail2ban
      tags:
        - fail2ban
    - role: network_failover
      tags:
        - network_failover
    - role: php_miio
      tags:
        - php_miio
    - role: restic
      tags:
        - restic
    - role: mhz19
      tags:
        - mhz19
    - role: docker
      tags:
        - docker
    - role: homeassistant_ha_secondary
      tags:
        - homeassistant_ha_secondary
