---
- name: Configure home primary
  hosts: home_primary
  become: true
  remote_user: ubuntu
  roles:
    - role: ubuntu
      tags:
        - ubuntu
    - role: raspberrypi
      tags:
        - raspberrypi
    - role: chezmoi
      tags:
        - chezmoi
    - role: postfix_client
      tags:
        - postfix_client
    - role: zabbix_agent
      tags:
        - zabbix_agent
    - role: fail2ban
      tags:
        - fail2ban
    - role: mhz19
      tags:
        - mhz19
    - role: autodiscover
      tags:
        - autodiscover
    - role: couchdb
      tags:
        - couchdb
    - role: docker
      tags:
        - docker
    - role: enecoq_data_fetcher
      tags:
        - enecoq_data_fetcher
    - role: filebrowser
      tags:
        - filebrowser
    - role: homeassistant
      tags:
        - homeassistant
    - role: homeassistant_ha_primary
      tags:
        - homeassistant_ha_primary
    - role: httpd
      tags:
        - httpd
    - role: litellm
      tags:
        - litellm
    - role: lmstudio
      tags:
        - lmstudio
    - role: matter_server
      tags:
        - matter_server
    - role: mosquitto
      tags:
        - mosquitto
    - role: nas
      tags:
        - nas
    - role: nvr
      tags:
        - nvr
    - role: syslogd
      tags:
        - syslogd
    - role: teslamate
      tags:
        - teslamate
    - role: zabbix_server
      tags:
        - zabbix_server
    - role: zabbix_mcp
      tags:
        - zabbix_mcp
    - role: zabbix_money_market
      tags:
        - zabbix_money_market
