---
- hosts: singleton_int1
  become: true
  remote_user: ubuntu
  roles:
    - autodiscover
    - couchdb
    - docker
    - enecoq-data-fetcher
    - homeassistant
    - homeassistant-ha/primary
    - httpd
    - litellm
    - lmstudio
    - matter-server
    - mosquitto
    - syslogd
    - zabbix/server
    - zabbix/mcp
    - zabbix/money/market
