---
- name: Import cloud workstation
  ansible.builtin.import_playbook: cloud-workstation.yml

- name: Import home primary
  ansible.builtin.import_playbook: home-primary.yml

- name: Import home secondary
  ansible.builtin.import_playbook: home-secondary.yml
