---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - desktop_package

- name: Import terminal tasks
  ansible.builtin.import_tasks: terminal.yml
  tags:
    - desktop_terminal
    - update
