---
- name: Reload Apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Restart aa-disable-homeassistant
  ansible.builtin.systemd:
    name: aa-disable-homeassistant
    state: restarted

- name: Restart Home Assistant
  community.docker.docker_compose_v2:
    project_src: /etc/compose/homeassistant
    state: restarted
  # The project directory may not exist yet in check mode.
  when: not ansible_check_mode

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
