---
- name: "apache: Reload"
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: "aa-disable-homeassistant: Restart"
  ansible.builtin.systemd:
    name: aa-disable-homeassistant
    state: restarted

- name: "apache: Restart"
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: "homeassistant: Restart"
  community.docker.docker_compose_v2:
    project_src: /etc/compose/homeassistant
    state: restarted
  # The project directory may not exist yet in check mode.
  when: not ansible_check_mode

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
