---
- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  tags:
    - couchdb_container
    - update

- name: Import deno tasks
  ansible.builtin.import_tasks: deno.yml
  tags:
    - couchdb_deno
    - update

- name: Import database tasks
  ansible.builtin.import_tasks: database.yml
  tags:
    - couchdb_database
    - update

- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - couchdb_apache
