---
raspberrypi_default_gateway: 192.168.0.1
raspberrypi_default_gateway6: fe80::70a7:41ff:fea6:bd7a
raspberrypi_resolved1:
  ip: 192.168.0.1
raspberrypi_xray_legacy_password: "{{ lookup('pipe', 'op read \"op://ansible/rumnirwx3xulltfgu33gx5tc2y/wireless network password\"') }}"
