---
raspberrypi_aws_vpc_cidr: 10.0.0.0/16
raspberrypi_default_gateway: 192.168.0.1
raspberrypi_default_gateway6: fe80::70a7:41ff:fea6:bd7a
raspberrypi_netgear_gs108tv3_version: 7.0.6.2
raspberrypi_php_miio_version: 0.2.6
raspberrypi_restic:
  password: "{{ lookup('pipe', 'op read \"op://ansible/restic/password\"') }}"
  version: 0.19.1
raspberrypi_resolved1:
  ip: 192.168.0.1
  ipv6: 240f:78:31e9:1:70a7:41ff:fea6:bd7a
raspberrypi_xray_password: "{{ lookup('pipe', 'op read \"op://ansible/xray/wireless network password\"') }}"
raspberrypi_xray_legacy_password: "{{ lookup('pipe', 'op read \"op://ansible/xray-legacy/wireless network password\"') }}"
