---
- name: Import certbot tasks
  ansible.builtin.import_tasks: certbot.yml
  tags:
    - sslcert_certbot
    - update

- name: Import timer tasks
  ansible.builtin.import_tasks: timer.yml
  tags:
    - sslcert_timer

- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - sslcert_apache
