---
- name: Import browser tasks
  ansible.builtin.import_tasks: browser.yml
  tags:
    - enecoq_data_fetcher_browser
    - update

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags:
    - enecoq_data_fetcher_service
