UserParameter=backup.daily.success_age,echo $(($(date +%s) - $(stat -c %Y /var/lib/backup-daily.success 2>/dev/null || echo 0)))
UserParameter=heat,echo "scale=3; $(cat /sys/class/thermal/thermal_zone0/temp) / 1000" | bc
