---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - chezmoi_package

- name: Import source tasks
  ansible.builtin.import_tasks: source.yml
  tags:
    - chezmoi_source
