---
- name: aliases | Set root mail alias
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    insertafter: "^postmaster:"
    regexp: "^root: "
    line: "root: {{ admin_email }}"
  notify: Rebuild aliases
