---
- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  tags:
    - nvr_container
    - update

- name: Import zabbix tasks
  ansible.builtin.import_tasks: zabbix.yml
  tags:
    - nvr_zabbix

- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - nvr_apache
