---
- name: fail2ban | Deploy filter
  ansible.builtin.template:
    src: fail2ban-filter.conf.j2
    dest: /etc/fail2ban/filter.d/filebrowser.conf
    mode: "0644"
  notify: Restart fail2ban

- name: fail2ban | Deploy jail config
  ansible.builtin.template:
    src: fail2ban-jail.conf.j2
    dest: /etc/fail2ban/jail.d/filebrowser.conf
    mode: "0644"
  notify: Restart fail2ban
