---
- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - filebrowser_config

- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  tags:
    - filebrowser_container
    - update

- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - filebrowser_apache

- name: Import fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  tags:
    - filebrowser_fail2ban
