#!/usr/bin/env python3

import sys
from pysesame3.auth import WebAPIAuth
from pysesame3.lock import CHSesame2

def main():
    try:
        command = sys.argv[1]
        api_key = sys.argv[2]
        uuid = sys.argv[3]
        secret = sys.argv[4]

        device = CHSesame2(WebAPIAuth(api_key), uuid, secret)

        if command == "lock":
            device.lock("Python")
        elif command == "unlock":
            device.unlock("Python")
        else:
            device.toggle("Python")
    except IndexError:
        print("Usage: sesame <lock|unlock|toggle> <api_key> <uuid> <secret>")

if __name__ == "__main__":
    main()
