---
- name: zabbix | Copy agent config
  ansible.builtin.template:
    src: homeassistant-ha.conf.j2
    dest: /etc/zabbix/zabbix_agentd.d/homeassistant-ha.conf
    mode: "0644"
    variable_start_string: "[%"
    variable_end_string: "%]"
  notify: Restart zabbix-agent
