---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart certbot timer
  ansible.builtin.systemd:
    name: certbot.timer
    state: restarted
    daemon_reload: true
