---
- name: Import rsyslog tasks
  ansible.builtin.import_tasks: rsyslog.yml
  tags:
    - syslogd_rsyslog

- name: Import logrotate tasks
  ansible.builtin.import_tasks: logrotate.yml
  tags:
    - syslogd_logrotate
