---
- name: Import publisher tasks
  ansible.builtin.import_tasks: publisher.yml
  tags:
    - mhz19_publisher
    - update

- name: Import timer tasks
  ansible.builtin.import_tasks: timer.yml
  tags:
    - mhz19_timer
