---
- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - litellm_apache

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - litellm_config

- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  tags:
    - litellm_container
    - update
