#!/bin/sh

JSONFILE=/tmp/upsert-zabbix-rewse-jp.json

# {{{ switch_dns()

switch_dns() {
  cat <<! > $JSONFILE
{
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "zabbix.rewse.jp.",
        "Type": "CNAME",
        "TTL": 300,
        "ResourceRecords": [
          {
            "Value": "zabbix$target.rewse.jp"
          }
        ]
      }
    }
  ]
}
!

  echo "Switching Private Type DNS..."
  aws route53 change-resource-record-sets --hosted-zone-id Z2I4KTTS0XIOSB --change-batch file://$JSONFILE

  rm -f $JSONFILE
}

# }}}
# {{{ Main

if [ `id -u` != 0 ]; then
  echo "<ERROR> Only root can execute"
  exit 1
fi

if [ "`hostname -s`" == "charlie" ]; then
  src=2
  target=1
elif [ "`hostname -s`" == "foxtrot" ]; then
  src=1
  target=2
else
  echo "<USAGE> failover-zabbix-server" >&2
  exit 1
fi

echo "Stopping zabbix-server on zabbix$src..."
ssh centos@zabbix$src sudo systemctl stop zabbix-server

echo "Starting zabbix-server here..."
sudo systemctl start zabbix-server

switch_dns
# }}}
