---
- name: ghostty | Copy terminfo
  ansible.builtin.copy:
    src: xterm-ghostty
    dest: /usr/share/terminfo/x/xterm-ghostty
    mode: "0644"

- name: ghostty | Link terminfo name
  ansible.builtin.file:
    src: ../x/xterm-ghostty
    dest: /usr/share/terminfo/g/ghostty
    state: link
