---
- name: Import facts tasks
  ansible.builtin.import_tasks: facts.yml
  tags:
    - always

- name: Import timezone tasks
  ansible.builtin.import_tasks: timezone.yml
  tags:
    - ubuntu_timezone

- name: Import apt tasks
  ansible.builtin.import_tasks: apt.yml
  tags:
    - ubuntu_apt
    - update

- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - ubuntu_package

- name: Import awscliv2 tasks
  ansible.builtin.import_tasks: awscliv2.yml
  tags:
    - ubuntu_awscliv2
    - update

- name: Import kiro_cli tasks
  ansible.builtin.import_tasks: kiro_cli.yml
  tags:
    - ubuntu_kiro_cli
    - update

- name: Import uv tasks
  ansible.builtin.import_tasks: uv.yml
  tags:
    - ubuntu_uv
    - update

- name: Import zinit tasks
  ansible.builtin.import_tasks: zinit.yml
  tags:
    - ubuntu_zinit
    - update

- name: Import etckeeper tasks
  ansible.builtin.import_tasks: etckeeper.yml
  tags:
    - ubuntu_etckeeper

- name: Import hostname tasks
  ansible.builtin.import_tasks: hostname.yml
  tags:
    - ubuntu_hostname

- name: Import inputrc tasks
  ansible.builtin.import_tasks: inputrc.yml
  tags:
    - ubuntu_inputrc

- name: Import user tasks
  ansible.builtin.import_tasks: user.yml
  tags:
    - ubuntu_user

- name: Import ssh tasks
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - ubuntu_ssh

- name: Import failure_notify tasks
  ansible.builtin.import_tasks: failure_notify.yml
  tags:
    - ubuntu_failure_notify

- name: Import ghostty tasks
  ansible.builtin.import_tasks: ghostty.yml
  tags:
    - ubuntu_ghostty

- name: Import skills tasks
  ansible.builtin.import_tasks: skills.yml
  tags:
    - ubuntu_skills

- name: Import agent_browser tasks
  ansible.builtin.import_tasks: agent_browser.yml
  tags:
    - ubuntu_agent_browser

- name: Import lightpanda tasks
  ansible.builtin.import_tasks: lightpanda.yml
  tags:
    - ubuntu_lightpanda
    - update

- name: Import npm tasks
  ansible.builtin.import_tasks: npm.yml
  tags:
    - ubuntu_npm
    - update

- name: Import upgrade tasks
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - ubuntu_upgrade
    - update
