---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - raspberrypi_package

- name: Import swap tasks
  ansible.builtin.import_tasks: swap.yml
  tags:
    - raspberrypi_swap

- name: Import ntp tasks
  ansible.builtin.import_tasks: ntp.yml
  tags:
    - raspberrypi_ntp

- name: Import journald tasks
  ansible.builtin.import_tasks: journald.yml
  tags:
    - raspberrypi_journald

- name: Import bluetooth tasks
  ansible.builtin.import_tasks: bluetooth.yml
  tags:
    - raspberrypi_bluetooth

- name: Import snmp tasks
  ansible.builtin.import_tasks: snmp.yml
  tags:
    - raspberrypi_snmp

- name: Import environment tasks
  ansible.builtin.import_tasks: environment.yml
  tags:
    - raspberrypi_environment

- name: Import nvme tasks
  ansible.builtin.import_tasks: nvme.yml
  tags:
    - raspberrypi_nvme

- name: Import network tasks
  ansible.builtin.import_tasks: network.yml
  tags:
    - raspberrypi_network

- name: Import ssh tasks
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - raspberrypi_ssh

- name: Import qwen_code tasks
  ansible.builtin.import_tasks: qwen_code.yml
  tags:
    - raspberrypi_qwen_code

- name: Import claude_code tasks
  ansible.builtin.import_tasks: claude_code.yml
  tags:
    - raspberrypi_claude_code
