---
- name: Reload Apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart filebrowser
  community.docker.docker_compose_v2:
    project_src: /etc
    services: filebrowser
    state: restarted
    pull: always
    recreate: always
