---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - power_monitor_package

- name: Import app tasks
  ansible.builtin.import_tasks: app.yml
  tags:
    - power_monitor_app
    - update

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - power_monitor_config
    - update
