---
darwin_extra_packages:
  - treefmt
  - vips

darwin_extra_casks:
  - charles
  - deepl
  - ea
  - fantastical
  - epic-games
  - gog-galaxy
  - google-cloud-sdk
  - kiro
  - kiro-cli
  - microsoft-office
  - raspberry-pi-imager
  - sony-ps-remote-play
  - steam
  - steelseries-gg
  - ticktick
