#!/usr/bin/env bash

set -euo pipefail
trap 'exit 1' 1 2 3 15

device_id=$1

if [ ! "$device_id" ]; then
    read -p "Device ID: " device_id
    exit 1
fi

# {{{ sendto_mqtt()

sendto_mqtt() {
    json=$(switchbotmeter $device_id)
    message=$(echo $json | jq -r .message)

    message=${message//success/online}

    if [ "$message" != "online" ]; then
        message=offline
    fi

    mosquitto_pub -r -t switchbotmeter/$device_id -m "$json"
    mosquitto_pub -r -t switchbotmeter/$device_id/status -m $message
}

# }}}
# {{{ Main

sendto_mqtt

# }}}
