#!/usr/bin/env bash

set -u
trap 'exit 1' 1 2 3 15

device_id=$1

if [ ! "$device_id" ]; then
    read -p "Device ID: " device_id
    exit 1
fi

# {{{ sendto_mqtt()

sendto_mqtt() {
    upper_device_id=${device_id//:/}
    upper_device_id=${upper_device_id^^}

    lower_device_id=${upper_device_id:0:2}:${upper_device_id:2:2}:${upper_device_id:4:2}:${upper_device_id:6:2}:${upper_device_id:8:2}:${upper_device_id:10:2}
    lower_device_id=${lower_device_id,,}

    rset=$(switchbotmeter-ble $lower_device_id Humiture | grep Meter)

    retval=$?

    if [ "$retval" == "0" ]; then
        datetime=$(date --iso-8601=seconds)
        temp=$(echo $rset | awk '{print $2}' | sed "s/'C//")
        humi=$(echo $rset | awk '{print $3}' | sed 's/%//')
        message=online

        json=$(cat <<!
{
    "datetime": "$datetime",
    "temperature": "$temp",
    "humidity": "$humi",
    "message": "$message",
    "method": "ble"
}
!
        )
    else
        json=$(switchbotmeter-api $upper_device_id)
        message=$(echo $json | jq -r .message)
    fi

    if [ "$message" != "success" ]; then
        message=online
    else
        message=offline
    fi

    mosquitto_pub -r -t switchbotmeter/$upper_device_id -m "$json"
    mosquitto_pub -r -t switchbotmeter/$upper_device_id/status -m $message
}

# }}}
# {{{ Main

sendto_mqtt

# }}}
