---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - mosquitto_package

- name: Import auth tasks
  ansible.builtin.import_tasks: auth.yml
  tags:
    - mosquitto_auth
