---
- name: Import set_vars tasks
  ansible.builtin.import_tasks: set_vars.yml
  tags:
    - always

- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - httpd_package

- name: Import default_site tasks
  ansible.builtin.import_tasks: default_site.yml
  tags:
    - httpd_default_site

- name: Import conf tasks
  ansible.builtin.import_tasks: conf.yml
  tags:
    - httpd_conf

- name: Import php tasks
  ansible.builtin.import_tasks: php.yml
  tags:
    - httpd_php

- name: Import zabbix tasks
  ansible.builtin.import_tasks: zabbix.yml
  tags:
    - httpd_zabbix
