---
- name: nix | Check installation
  ansible.builtin.stat:
    path: /nix/var/nix/profiles/default/bin/nix
  register: __nix_binary

- name: nix | Download installer
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix-install.sh
    mode: "0755"
  become: "{{ not ansible_check_mode }}"
  when: not __nix_binary.stat.exists

- name: nix | Install
  # The vendor installer has no module.
  ansible.builtin.command: sh /tmp/nix-install.sh --yes
  args:
    creates: /nix/var/nix/profiles/default/bin/nix
  become: "{{ not ansible_check_mode }}"
  when: not __nix_binary.stat.exists

- name: nix | Check current version
  ansible.builtin.command: /nix/var/nix/profiles/default/bin/nix --version
  changed_when: false
  check_mode: false
  register: __nix_current_version_command
  when: __nix_binary.stat.exists

- name: nix | Check latest stable version
  ansible.builtin.command:
    argv:
      - /nix/var/nix/profiles/default/bin/nix
      - --extra-experimental-features
      - nix-command
      - upgrade-nix
      - --dry-run
      - --profile
      - /nix/var/nix/profiles/default
  changed_when: false
  check_mode: false
  register: __nix_upgrade_check
  when: __nix_binary.stat.exists

- name: nix | Parse versions
  ansible.builtin.set_fact:
    __nix_current_version: >-
      {{ __nix_current_version_command.stdout |
      regex_findall('[0-9]+(?:\.[0-9]+)+') | first }}
    __nix_upgrade_version: >-
      {{ __nix_upgrade_check.stderr |
      regex_findall('would upgrade to version ([0-9]+(?:\.[0-9]+)+)') |
      first | default('') }}
  when: __nix_binary.stat.exists

- name: nix | Update
  ansible.builtin.command:
    argv:
      - /nix/var/nix/profiles/default/bin/nix
      - --extra-experimental-features
      - nix-command
      - upgrade-nix
      - --profile
      - /nix/var/nix/profiles/default
  become: "{{ not ansible_check_mode }}"
  changed_when: true
  when:
    - __nix_binary.stat.exists
    - __nix_upgrade_version | length > 0
    - >-
      __nix_upgrade_version is version(
      __nix_current_version, '>')
