---
- name: "docker : Install packages"
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
      - python3-docker
      - skopeo
  tags:
    - docker
    - install
    - docker_docker
    - docker_docker_install

- name: "docker : Add admin user to docker group"
  ansible.builtin.user:
    name: "{{ admin }}"
    groups: docker
    append: true
  tags:
    - docker
    - config
    - docker_docker
    - docker_docker_config

- name: "docker : Create compose.yml"
  ansible.builtin.file:
    path: /etc/compose.yml
    state: touch
    mode: '0644'
  tags:
    - docker
    - init
    - docker_docker
    - docker_docker_init

- name: "docker : Add services section to compose.yml"
  ansible.builtin.lineinfile:
    path: /etc/compose.yml
    insertbefore: BOF
    regexp: '^services:'
    line: 'services:'
  tags:
    - docker
    - init
    - docker_docker
    - docker_docker_init
    - docker_docker_config
