---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - docker_package

- name: Import group tasks
  ansible.builtin.import_tasks: group.yml
  tags:
    - docker_group

- name: Import daemon tasks
  ansible.builtin.import_tasks: daemon.yml
  tags:
    - docker_daemon

- name: Import compose tasks
  ansible.builtin.import_tasks: compose.yml
  tags:
    - docker_compose
