---
- name: package | Install zabbix-release package
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/{{ zabbix_server_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_server_version }}+ubuntu{{ ansible_facts['distribution_version'] }}_all.deb
  retries: 3
  delay: 5
  register: __zabbix_server_release
  until: __zabbix_server_release is succeeded

- name: package | Install packages
  ansible.builtin.apt:
    name:
      - fonts-noto-cjk
      - fping
      - mosquitto-clients
      - php-pgsql
      - zabbix-apache-conf
      - zabbix-frontend-php
      - zabbix-get
      - zabbix-server-pgsql
    update_cache: true
  notify: Restart Apache
