---
- name: Import storage tasks
  ansible.builtin.import_tasks: storage.yml
  tags:
    - nas_storage

- name: Import nfs tasks
  ansible.builtin.import_tasks: nfs.yml
  tags:
    - nas_nfs

- name: Import samba tasks
  ansible.builtin.import_tasks: samba.yml
  tags:
    - nas_samba

- name: Import s3 tasks
  ansible.builtin.import_tasks: s3.yml
  tags:
    - nas_s3

- name: Import zabbix tasks
  ansible.builtin.import_tasks: zabbix.yml
  tags:
    - nas_zabbix
