---
enecoq_data_fetcher_enecoq:
  email: "{{ lookup('pipe', 'op read op://ansible/ylie2zpjuu2nnp5sym3vejwlcq/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/ylie2zpjuu2nnp5sym3vejwlcq/credential') }}"
