---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - homeassistant_package

- name: Import certs tasks
  ansible.builtin.import_tasks: certs.yml
  tags:
    - homeassistant_certs

- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  tags:
    - homeassistant_container
    - update

- name: Import apparmor tasks
  ansible.builtin.import_tasks: apparmor.yml
  tags:
    - homeassistant_apparmor

- name: Import configuration tasks
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - homeassistant_configuration

- name: Import automation tasks
  ansible.builtin.import_tasks: automation.yml
  tags:
    - homeassistant_automation

- name: Import card_mod tasks
  ansible.builtin.import_tasks: card_mod.yml
  tags:
    - homeassistant_card_mod
    - update

- name: Import echonet_lite tasks
  ansible.builtin.import_tasks: echonet_lite.yml
  tags:
    - homeassistant_echonet_lite
    - update

- name: Import frigate tasks
  ansible.builtin.import_tasks: frigate.yml
  tags:
    - homeassistant_frigate
    - update

- name: Import frosted_glass tasks
  ansible.builtin.import_tasks: frosted_glass.yml
  tags:
    - homeassistant_frosted_glass
    - update

- name: Import mini_graph_card tasks
  ansible.builtin.import_tasks: mini_graph_card.yml
  tags:
    - homeassistant_mini_graph_card
    - update

- name: Import mini_media_player tasks
  ansible.builtin.import_tasks: mini_media_player.yml
  tags:
    - homeassistant_mini_media_player
    - update

- name: Import simple_weather_card tasks
  ansible.builtin.import_tasks: simple_weather_card.yml
  tags:
    - homeassistant_simple_weather_card
    - update

- name: Import tuya tasks
  ansible.builtin.import_tasks: tuya.yml
  tags:
    - homeassistant_tuya
    - update

- name: Import tesla_fleet tasks
  ansible.builtin.import_tasks: tesla_fleet.yml
  tags:
    - homeassistant_tesla_fleet

- name: Import apache tasks
  ansible.builtin.import_tasks: apache.yml
  tags:
    - homeassistant_apache

- name: Import fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  tags:
    - homeassistant_fail2ban
