#!/bin/sh

JSONFILE=/tmp/upsert-mail-rewse-jp.json

# {{{ switch_dns()

switch_dns() {
  cat <<! > $JSONFILE
{
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "mail.rewse.jp.",
        "Type": "CNAME",
        "TTL": 300,
        "ResourceRecords": [
          {
            "Value": "mail$target.rewse.jp"
          }
        ]
      }
    }
  ]
}
!

  echo "Switching Private Type DNS..."
  aws route53 change-resource-record-sets --hosted-zone-id Z2I4KTTS0XIOSB --change-batch file://$JSONFILE

  echo "Switching Public Type DNS..."
  aws route53 change-resource-record-sets --hosted-zone-id Z34LVKL0P9KD74 --change-batch file://$JSONFILE

  rm -f $JSONFILE
}

# }}}
# {{{ Main

if [ `id -u` != 0 ]; then
  echo "<ERROR> Only root can execute"
  exit 1
fi

if [ "`hostname -s`" == "charlie" ]; then
  src=2
  target=1
elif [ "`hostname -s`" == "foxtrot" ]; then
  src=1
  target=2
else
  echo "<USAGE> failover-mail" >&2
  exit 1
fi

echo "Stopping postfix on mail$src..."
ssh centos@mail$src sudo systemctl stop postfix

echo "Stopping dovecot on mail$src..."
ssh centos@mail$src sudo systemctl stop dovecot

echo "Wait 20 seconds to finish lsync..."
for i in `seq 1 20`; do
  sleep 1
  echo -n "."
done
echo ""

echo "Stopping lsyncd on mail$src..."
ssh centos@mail$src sudo systemctl stop lsyncd

echo "Starting lsyncd here..."
sudo systemctl start lsyncd

switch_dns

echo "Starting postfix on mail$src..."
ssh centos@mail$src sudo systemctl start postfix

echo "Starting dovecot on mail$src..."
ssh centos@mail$src sudo systemctl start dovecot

# }}}
