---
- name: "systemd-journald: Restart"
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: "systemd-timesyncd: Restart"
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: "dphys-swapfile: Restart"
  ansible.builtin.systemd:
    name: dphys-swapfile
    state: restarted

- name: "ssh: Restart socket"
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted

- name: "network-failover: Restart timer"
  ansible.builtin.systemd:
    name: network-failover.timer
    state: restarted
    daemon_reload: true

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "raspberrypi : Restart local backup timer"
  ansible.builtin.systemd:
    name: "restic-local-backup@{{ ansible_facts['hostname'] }}.timer"
    state: restarted
    daemon_reload: true

- name: "raspberrypi : Restart local check timer"
  ansible.builtin.systemd:
    name: "restic-local-check@{{ ansible_facts['hostname'] }}.timer"
    state: restarted
    daemon_reload: true

- name: "raspberrypi : Restart S3 backup timer"
  ansible.builtin.systemd:
    name: "restic-s3-backup@{{ ansible_facts['hostname'] }}.timer"
    state: restarted
    daemon_reload: true

- name: "raspberrypi : Restart S3 check timer"
  ansible.builtin.systemd:
    name: "restic-s3-check@{{ ansible_facts['hostname'] }}.timer"
    state: restarted
    daemon_reload: true

- name: "sysctl: Reload"
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: "udev: Reload rules"
  ansible.builtin.command: udevadm control --reload-rules
  changed_when: false
