---
zabbix_server:
  db_host: "{{ lookup('pipe', 'op read \"op://ansible/hrmsun2hbhhvrr6ou6yungdfwi/server\"') }}"
  db_password: "{{ lookup('pipe', 'op read \"op://ansible/hrmsun2hbhhvrr6ou6yungdfwi/password\"') }}"
  version: 7.4
