---
- name: "matter-server: Restart"
  community.docker.docker_compose_v2:
    project_src: /etc/compose/matter_server
    state: restarted
  # The project directory may not exist yet in check mode.
  when: not ansible_check_mode
