---
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - ec2_package

- name: Import storage tasks
  ansible.builtin.import_tasks: storage.yml
  tags:
    - ec2_storage
