---
- name: Import app tasks
  ansible.builtin.import_tasks: app.yml
  tags:
    - zabbix_money_market_app
    - update

- name: Import browser tasks
  ansible.builtin.import_tasks: browser.yml
  tags:
    - zabbix_money_market_browser
    - update

- name: Import timer tasks
  ansible.builtin.import_tasks: timer.yml
  tags:
    - zabbix_money_market_timer
