---
- id: automation.refresh_tesla_fleet_data
  alias: "Refresh Tesla Fleet Data"
  triggers:
    - trigger: template
      value_template: >-
        {{ states('sensor.model_y_state') in ['Online', 'Driving', 'Charging'] }}
    - trigger: time_pattern
      minutes: "/10"
      seconds: 43
  conditions:
    - condition: template
      value_template: >-
        {{ states('sensor.model_y_state') in ['Online', 'Driving', 'Charging'] }}
  actions:
    - action: homeassistant.update_entity
      target:
        entity_id: climate.model_y_climate
  mode: single
  trace:
    stored_traces: 100
