- id: automation.info_aplus
  alias: "INFO: Aplus"
  triggers:
    - trigger: state
      entity_id: sensor.aplus
  conditions:
    - "{{ (as_timestamp(now()) - as_timestamp(state_attr('sensor.aplus', 'Date'))) < 180 }}"
  actions:
    - delay:
        seconds: 5
    - action: notify.tats_devices
      data:
        title: "💳 Luxury Card"
        message: "{{ states('sensor.aplus_time') }}に{{ states('sensor.aplus_amount') }}円の利用がありました"
        data:
          push:
            interruption-level: time-sensitive
          url: "/lovelace/others"
- id: automation.info_hills_card
  alias: "INFO: HILLS CARD"
  triggers:
    - trigger: state
      entity_id: sensor.hills_card
  conditions:
    - "{{ (as_timestamp(now()) - as_timestamp(state_attr('sensor.hills_card', 'Date'))) < 180 }}"
    - condition: template
      value_template: >-
        {{
          is_number(states('sensor.hills_card_amount')) and
          states('sensor.hills_card_time') |
          regex_match('^[0-9]{1,2}:[0-9]{2}$')
        }}
  actions:
    - delay:
        seconds: 5
    - action: notify.tats_devices
      data:
        title: "💳 HILLS CARD"
        message: "{{ states('sensor.hills_card_time') }}に{{ states('sensor.hills_card_amount') }}円の利用がありました"
        data:
          push:
            interruption-level: time-sensitive
          url: "/lovelace/others"
- id: automation.info_mamorail
  alias: "INFO: Mamorail"
  triggers:
    - trigger: state
      entity_id: sensor.mamorail
  conditions:
    - "{{ (as_timestamp(now()) - as_timestamp(state_attr('sensor.mamorail', 'Date'))) < 180 }}"
  actions:
    - delay:
        seconds: 5
    - variables:
        charge: ""
        particle: ""
    - if:
        - condition: numeric_state
          entity_id: sensor.mamorail_balance
          below: 1000
      then:
        - variables:
            charge: "【要チャージ】"
    - if:
        - condition: state
          entity_id: sensor.mamorail_action
          state: "入場"
      then:
        - variables:
            particle: "に"
      else:
        - variables:
            particle: "を"
    - action: notify.all_devices
      data:
        title: "🐈 INFO"
        message: "{{ charge }}{{ states('sensor.mamorail_station') }}{{ particle }}{{ states('sensor.mamorail_time') }}に{{ states('sensor.mamorail_action') }}しました。残高: {{ states('sensor.mamorail_balance') }}円"
        data:
          push:
            interruption-level: time-sensitive
          url: "/lovelace/others"
- id: automation.info_mll
  alias: "INFO: MLL"
  triggers:
    - trigger: state
      entity_id: sensor.mll
  conditions:
    - "{{ (as_timestamp(now()) - as_timestamp(state_attr('sensor.mll', 'Date'))) < 180 }}"
  actions:
    - delay:
        seconds: 5
    - variables:
        particle: ""
    - if:
        - condition: state
          entity_id: sensor.mll_action
          state: "入室"
      then:
        - variables:
            particle: "に"
      else:
        - variables:
            particle: "を"
    - action: notify.all_devices
      data:
        title: "🐈 INFO"
        message: "MLL{{ particle }}{{ states('sensor.mll_time') }}に{{ states('sensor.mll_action') }}しました"
        data:
          push:
            interruption-level: time-sensitive
          url: "/lovelace/others"
